### ISSUE TITLE
[Feature] Adicionar botão de `continuar` na atividade /comecar/geral/meu-nome/meu-primeiro-nome/2

### ISSUE THREAD

**Issue by antnathan** [lmedesenvolvimento/luz-do-saber-portal#4]
Adicionar o botão de continuar.
![image](https://user-images.githubusercontent.com/25112415/189237728-a5f3603a-d09a-4ebd-9276-2aec99ce415a.png)

**Comment by antnathan** [comment]
Não mais finalizar a atividade ao realizar o upload. Mas sim ao clicar no botão de continuar que deve estar em baixo do crachá e alinhado ao centro.

**Comment by netosouza22** [comment]
![image](https://user-images.githubusercontent.com/63481821/190495748-8fa1c891-456c-4e62-ab6c-87c2ac156cca.png)
adicionado o seguinte botão
